// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jcasmmedljaglyjamjab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjYXNtbWVkbGphZ2x5amFtamFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMjM1NTQsImV4cCI6MjA3MzU5OTU1NH0.meCnRvoP3Y4-zq5b0rrrTXlW4bVx3cPfhT5IghpJm9E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});